[package]
name = "deep_causality_physics"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
authors = ["Marvin Hansen <marvin.hansen@gmail.com>"]

[dependencies]
deep_causality_haft = { workspace = true }
deep_causality_num = { workspace = true }
deep_causality_rand = { workspace = true }
deep_causality_tensor = { workspace = true }
deep_causality_topology = { workspace = true }
rayon = { workspace = true }
